### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by notjacobjun** [yash9263/Solitude-admin-client#1]
Login returning users and have a button for new users to register

**Comment by yash9263** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/35724199/107241999-87501600-6a51-11eb-8a13-b26fd1373604.png)
![Screenshot (15)](https://user-images.githubusercontent.com/35724199/107242068-9cc54000-6a51-11eb-80b3-22a004258cad.png)
login and sign up page

**Comment by yash9263** [comment]
how are you planning on connecting it with backend.

**Comment by notjacobjun** [comment]
I am going to look into that today, just curious am I the only one who is new to using microservice design paradigm?

**Comment by yash9263** [comment]
I have implemented the firebase authentication.
